name: ðŸ› Library Bug Report
description: Report a bug in the browser-use Python library
labels: ["bug", "triage"]
title: "Bug: ..."
assignees:
  - pirate
body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       Thanks for taking the time to fill out this bug report! Please fill out the form below to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: Browser Use Version
      description: What version of the `browser-use` library are you using? (Run `uv pip show browser-use` or `git log -n 1` to find out) **DO NOT JUST WRITE `latest version` or `main`**
      placeholder: "e.g. 0.4.45 or 62760baaefd"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description, Steps to Reproduce, Screenshots
      description: A clear and concise description of what the bug is + steps taken, drag screenshots in showing any error messages and relevant pages.
      placeholder: |
        1. Installed browser-use library by running: `uv pip install browser-use`
        2. Installed the browser by running: `playwright install chromium --with-deps`
        3. Ran the code below with the following prompt: `go to example.com and do xyz...`
        4. Agent crashed and showed the following error: ...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Failing Python Code
      description: Include the exact python code you ran that encountered the issue, redact any sensitive URLs and API keys.
      render: python
      placeholder: |
        from dotenv import load_dotenv
        load_dotenv()
        from browser_use import Agent, BrowserSession, Controller
        from langchain_openai import ChatOpenAI

        llm = ChatOpenAI(model="gpt-4o")
        browser_session = BrowserSession(executable_path='/usr/bin/google-chrome')
        agent = Agent(llm=llm, browser_session=browser_session)
        ...

  - type: dropdown
    id: model
    attributes:
      label: LLM Model
      description: Which LLM model(s) are you using?
      multiple: true
      options:
        - gpt-4o
        - gpt-4o-mini
        - gpt-4
        - gpt-4.1
        - gpt-4.1-mini
        - gpt-4.1-nano
        - claude-3.7-sonnet
        - claude-3.5-sonnet
        - gemini-2.6-flash-preview
        - gemini-2.5-pro
        - gemini-2.0-flash
        - gemini-2.0-flash-lite
        - gemini-1.5-flash
        - deepseek-chat
        - Local Model (Specify model in description)
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "e.g., macOS 13.1, Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Full DEBUG Log Output
      description: Please copy and paste the *full* log output *from the start of the run*. Make sure to set `BROWSER_USE_LOG_LEVEL=DEBUG` in your `.env` or shell environment.
      render: shell
      placeholder: |
        $ python /app/browser-use/examples/browser/real_browser.py
        DEBUG    [browser] ðŸŒŽ  Initializing new browser
        DEBUG    [agent] Version: 0.1.46-9-g62760ba, Source: git
        INFO     [agent] ðŸ§  Starting an agent with main_model=gpt-4o +tools +vision +memory, planner_model=None, extraction_model=gpt-4o
        DEBUG    [agent] Verifying the ChatOpenAI LLM knows the capital of France...
        DEBUG    [langsmith.client] Sending multipart request with context: trace=91282a01-6667-48a1-8cd7-21aa9337a580,id=91282a01-6667-48a1-8cd7-21aa9337a580
        DEBUG    [agent] ðŸªª LLM API keys OPENAI_API_KEY work, ChatOpenAI model is connected & responding correctly.
        ...

  - type: markdown
    attributes:
      value: |
        ---
        > [!IMPORTANT]
        > ðŸ™ Please **go check *right now before submitting* that that you are on the [NEWEST VERSION](https://github.com/browser-use/browser-use/releases)**. We might've already shipped a fix for this yesterday!  
        > (If you are running an old version, the **first thing we will ask you to do is try the latest version**)
